FROM ubuntu
USER root
RUN apt update
RUN apt -y install whois tor netbase

WORKDIR /work/
RUN chmod "g+rwX" /work
COPY target/*-runner /work/application

EXPOSE 8080

#CMD ["/etc/init.d/tor start;/work/application", "-Dquarkus.http.host=0.0.0.0"]
ENTRYPOINT ["bash", "-c", "/etc/init.d/tor start;./application", "-Dquarkus.http.host=0.0.0.0"]