name: CI Build

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v5.1.0
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          destination_dir: ./
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
          
      - name: setup-maven-settings
        uses: s4u/maven-settings-action@v1
        with:
          servers: '[{"id": "github", "username": "x-access-token", "password": "${GITHUB_TOKEN}"}]'

      - name: deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          java --version
          mvn -ntp deploy -DskipTests

          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD

          docker build -f src/main/docker/Dockerfile.jvm -t torify-whois-quarkus .
          docker tag torify-whois-quarkus ozkanpakdil/torify-whois-quarkus
          docker push ozkanpakdil/torify-whois-quarkus

          mvn package -P native -DskipTests
          docker build -f src/main/docker/Dockerfile.native -t torify-whois-quarkus-graalvm .
          docker tag torify-whois-quarkus-graalvm ozkanpakdil/torify-whois-quarkus-graalvm
          docker push ozkanpakdil/torify-whois-quarkus-graalvm
